### ISSUE TITLE
GPL

### ISSUE THREAD

**Issue by jonasstein** [trapd00r/vidir#15]
Thank you for vidir. I like it very much. 
Can you specify with GPL is meant?
IANAL, but I think the GPL header and GPL license text are missing in the repository.

Best,
JS

**Comment by Tsutsukakushi** [comment]
The project seems to be a fork of [moreutils'](https://joeyh.name/code/moreutils/) vidir which is licensed under just GPL. Each version of the GPL includes the following clause:

```
If the Program does not specify a version number of the license, you may choose any version ever published by the Free Software Foundation.
```

**Comment by trapd00r** [comment]
Correct.
