### ISSUE TITLE
Not findable on CPAN

### ISSUE THREAD

**Issue by chreekat** [trapd00r/vidir#16]
vidir can still be [downloaded from CPAN](https://www.cpan.org/modules/by-authors/id/W/WO/WOLDRICH/), but can't be found in search nor by browsing your [author page on metacpan](https://metacpan.org/author/WOLDRICH). Do you know why this is?

Thanks!

**Comment by trapd00r** [comment]
Thanks for bringing it to my attention. Yes; it's because of some missing metadata in Makefile.PL. I'll get right on it.

**Comment by trapd00r** [comment]
https://metacpan.org/pod/release/WOLDRICH/App-vidir-0.042/bin/vidir

It should be installable now once the servers are in sync.

**Comment by trapd00r** [comment]
```
% cpan App::vidir
Successfully installed App-vidir-0.042
1 distribution installed

```

**Comment by chreekat** [comment]
Great! (But it looks like you haven't pushed your changes yet..)

By the way, I guess I should mention I am "maintaining" the distro package for NixOS: https://nixos.org/nixos/packages.html#vidir . I need to update it a bit. Just fyi.
