### ISSUE TITLE
vidir deleted my files

### ISSUE THREAD

**Issue by shivams** [trapd00r/vidir#25]
I renamed all my files using vidir in a folder using `vidir` and all the files just vanished after I closed vidir. They are not even in the trash folder. They were not important files (and I can re-download them). But I am scared about why this happened. I will come back and add instructions for reproducing the scenario. But had anyone ever witnessed this? This is scary.

**Comment by trapd00r** [comment]
What am I supposed to do here without any sort of information about the steps you took?

**Comment by shivams** [comment]
Pardon me for raising the issue without full information. I was AFK but am back now. I figured it was a far-fetched edge case which one would very rarely encounter. What happened is that I deleted all the file names and just typed them again to rename them, but I added a dot (`.`) after the numbers (of the numbered list items). But there were no dots in the original list item numbers. This made `vidir` to create a directory starting with a dot (hence a hidden directory) and then put all those renamed files within that directory. And since the directory was hidden, I thought my files had been deleted. If I had used the `--verbose` option, of course that would have showed me what happened.

To give clarity, what happened is this:

```shell
#original file names:
1 ./file1.txt
2 ./file2.txt

#I changed them to:
1. ./fileA.txt
2. ./fileB.txt
```

Anyways, this was a silly mistake at my end. But, in future, if something similar to this comes up for someone else, the first thing for them to do would be to use the `--verbose` option to see what's happening, or to just check the hidden directories. Or perhaps `vidir` could maintain some logs somewhere? Anyways, closing the issue for this minor edge case (that may never be encountered again). Thank you for your prompt response, though, @trapd00r :smiley:
